version: 2.1

orbs:
  orb_sample: tarappo/orb_sample@0.0.3
  sample_two: tarappo/sample_two@0.0.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - orb_sample/sample_command
      - sample_two/sample_two
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
