version: 2.1

orbs:
  sample: tarappo/sample@0.0.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - sample/sample:
          sample_key_value: "sample command!!!!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
