version: 2.1

orbs:
  orb_sample: tarappo/orb_sample@0.0.2

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - orb_sample/sample
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
